### ISSUE TITLE
CSV support on a released version

### ISSUE THREAD

**Issue by tbsvttr** [kgiszczak/shale#14]
Hi! I just discovered this cool library some days ago, and it seems to me like the most versatile and powerful serializer around in the Ruby space. Especially the capability to have JSON, XML, and CSV as a target from the same serializer could prove very useful in a recent project of mine.

However, I realized that the CSV capability is only available on the master branch at the moment. Is there any time schedule to do a release with it?

**Comment by kgiszczak** [comment]
hey, thanks,

I don't have a schedule, I was planing on implementing a few minor improvements to JSON and XML schema generators,
but I don't know how much it's gonna take, a rough estimate would be a month or so.

Is there a reason you can't use git repo directly (e.g. https://bundler.io/guides/git.html)?

**Comment by tbsvttr** [comment]
> Is there a reason you can't use git repo directly (e.g. https://bundler.io/guides/git.html)?

We actually do this in our prototype at the moment. However, including a master branch of a library that is comparatively new might raise some eyebrows with the stakeholders we are developing for. So I would like to avoid that.

**Comment by kgiszczak** [comment]
I see, I'll make a release next week then

**Comment by kgiszczak** [comment]
Hey, I just release v0.9.0 with CSV support. Changelog: https://github.com/kgiszczak/shale/blob/master/CHANGELOG.md
