### ISSUE TITLE
render_nil as a global setting

### ISSUE THREAD

**Issue by feliperaul** [kgiszczak/shale#17]
Hi! Thank you for this great gem. Would you consider making `render_nil` a global setting, like `Shale.render_nil = true` ?

**Comment by kgiszczak** [comment]
Hey, yeah, I'll do something like that, but instead of a global setting I was thinking about making it a field on mapping, eg:

```ruby
class Base < Shale::Mapper
  json do
    render_nil true
  end
end

class Address < Base
end
```

That way you could have more fine grained control over what default and where you want to use.

**Comment by feliperaul** [comment]
Makes sense!

**Comment by kgiszczak** [comment]
It's ready for testing on master branch. I'll do a new version release in a few weeks.

**Comment by feliperaul** [comment]
@kgiszczak I'm testing on `master`,  but noticed that it still doesn't render nil values with the `to_hash` transform.

**Comment by kgiszczak** [comment]
Hey do you have an example? When I set it on hash mapping it seems to work correctly, e.g:

```ruby
require 'shale'

class Person < Shale::Mapper
  attribute :first_name, Shale::Type::String
  attribute :last_name, Shale::Type::String

  hsh do
    render_nil true

    map 'first_name', to: :first_name
    map 'last_name', to: :last_name
  end
end

puts Person.new(first_name: 'John').to_hash
```

It gives me this output:

```ruby
{"first_name"=>"John", "last_name"=>nil}
```
