### ISSUE TITLE
shalerb.org is crashing chrome

### ISSUE THREAD

**Issue by feliperaul** [kgiszczak/shale#18]
Even in icognito tab:

![image](https://user-images.githubusercontent.com/743879/212152691-ec5025af-831b-4e9e-b382-4791d9dbb040.png)

**Comment by kgiszczak** [comment]
I tested it on Chrome, Firefox, Safari, Brave on Mac and it works ok for me.
Can you share more details on your system? Is it Windows, Linux?
Can paste console output?

**Comment by feliperaul** [comment]
I tested it again today and it's working fine!

There was no console output at the time;  Chrome's devtools just stated "devtools has disconnected". 

I'm on MacOs Ventura.

I'll reopen if it happens again. Go figure.
