### ISSUE TITLE
Cutting new release?

### ISSUE THREAD

**Issue by bcgraham** [kgiszczak/shale#22]
Big fan of this gem. The new `render_nil` stuff would be extremely useful for my team. Any chance you could cut a new release?

**Comment by kgiszczak** [comment]
Yeah, I've been getting to it for some time, I'll make a release on weekend.

**Comment by kgiszczak** [comment]
I just released v1.0.0, closing this ticket, let me know if you have anything more.

**Comment by bcgraham** [comment]
Thanks very much for getting this out - much appreciated!
