### ISSUE TITLE
Non obvious behaviour for usage with configuration block

### ISSUE THREAD

**Issue by Tab10id** [kgiszczak/shale#3]
There two mappers that by my mind should work identically:
```ruby
require 'shale'

class OnePerson < Shale::Mapper
  xml do
    root 'Person'
  end
  
  attribute :name, Shale::Type::String
end

class AnotherPerson < Shale::Mapper  
  attribute :name, Shale::Type::String

  xml do
    root 'Person'
  end
end

puts OnePerson.new(name: 'John Doe').to_xml(:pretty)
# <Person>
#   <name>John Doe</name>
# </Person>

puts AnotherPerson.new(name: 'John Doe').to_xml(:pretty)
# <Person/>
```
After little research I recognized that xml method fully override config setted by `attribute` method calls.
It's not critical but I think that it should be documented as minimum.

**Comment by kgiszczak** [comment]
Thanks for pointing that out.

That's an oversight on my side. Both should work the same and the second version's output is intended.
When you use `xml` block it should override default mapping created by `attribute` methods.

I'll fix it in next version.

**Comment by kgiszczak** [comment]
Full override is intended, because in most cases when you define your own mapping you don't need the default one.

But you always have access to the mapping object and can modify it however you want, so in your case something like this would work:
```ruby
class Person < Shale::Mapper
  attribute :name, Shale::Type::String
end

Person.xml_mapping.root('foo')

Person.new(name: 'John Doe').to_xml(:pretty)
# =>
#
# <foo>
#   <name>John Doe</name>
# </foo>
```

**Comment by Tab10id** [comment]
Ok. I like it.
Little fix:
```ruby
class Person < Shale::Mapper
  attribute :name, Shale::Type::String
  
  xml_mapping.root('foo')
end

Person.new(name: 'John Doe').to_xml(:pretty)
# =>
#
# <foo>
#   <name>John Doe</name>
# </foo>
```
