### ISSUE TITLE
Ability to pass options to YAML options

### ISSUE THREAD

**Issue by jwhitcraft** [kgiszczak/shale#32]
Saying i have a YAML file that uses aliases, it would be nice to be able pass in the options to the yaml adapter.

Eg:
```
Person.from_yaml(yaml, aliases: true)
```

I see this is done for CSV it would be nice to extend it to the default yaml adapter.

**Comment by kgiszczak** [comment]
Thank you for this suggestion. You should be able to do this on master now.
