### ISSUE TITLE
JSON map attributes are ignored when calling `as_json`

### ISSUE THREAD

**Issue by BoboFraggins** [kgiszczak/shale#34]
Given the following mapper:

```
class Test < Shale::Mapper
  attribute :nil_attribute, Shale::Type::String
  attribute :rails_attribute_name, Shale::Type::String

  json do
    map 'nil_attribute', to: :nil_attribute, render_nil: true
    map 'json_attribute_name', to: :rails_attribute_name
  end
end
```

I would expect both of these calls to generate the same hash:

```
irb(main):004> JSON.parse(Test.new(rails_attribute_name: 'foobar').to_json)
=> {"nil_attribute"=>nil, "json_attribute_name"=>"foobar"}
```

```
irb(main):003> Test.new(rails_attribute_name: 'foobar').as_json
=> {"rails_attribute_name"=>"foobar"}
```

But `as_json` ignores the attribute name change and the `render_nil` option.

I am happy to take a crack at fixing this, but before trying to I wanted to confirm that you believe this is a bug.

**Comment by kgiszczak** [comment]
Shale doesn't provide `as_json` method on an object instance. This method is only available on a class level e.g `Test.as_json(Test.new)`.

I think some other library might bleed into your objects (e.g Rails).

Here's an example showing that everything works correctly:
```ruby
class Test < Shale::Mapper
  attribute :nil_attribute, Shale::Type::String
  attribute :rails_attribute_name, Shale::Type::String

  json do
    map 'nil_attribute', to: :nil_attribute, render_nil: true
    map 'json_attribute_name', to: :rails_attribute_name
  end
end

puts Test.to_json(Test.new)
puts Test.as_json(Test.new)
```

The output is this:
```console
{"nil_attribute":null}
{"nil_attribute"=>nil}
```

**Comment by BoboFraggins** [comment]
Gotcha. Thanks for the response, love the gem!
