### ISSUE TITLE
Allow to render empty nodes in xml if value is nil

### ISSUE THREAD

**Issue by Tab10id** [kgiszczak/shale#4]
For some reasons we need to render empty xml nodes even if actual value absence.
For now the only available solution to add `|| ''` for every attributes in decorator.
Similar feature we have in representable:
https://trailblazer.to/2.1/docs/representable.html#representable-function-api-render-nil
Do you have plans to implement such feature?
I understand that it can make deserialization process more complicated.

**Comment by kgiszczak** [comment]
Hey, I just released a new version that solves this. You can use `render_nil: true` to control rendering. Release notes are here: https://www.shalerb.org/releases.html#v070

I'll close the issue, if you need anything create a new one, thanks.
