### ISSUE TITLE
Implement equality checks on `Shale::Mapper`

### ISSUE THREAD

**Issue by TastyPi** [kgiszczak/shale#41]
When defining models with `Shale::Mapper`, it would be nice if `==`, `#eql?`, and `hash` worked as you would expect.

Or if there is a recommended alternative for automatically implementing equality that could be documented that would be useful.

**Comment by kgiszczak** [comment]
What do you mean? Something like this?

```ruby
u1 = User.from_xml(<<~END)
  <user>
    <first_name>John</first_name>
    <last_name>Doe</last_name>
  </user>
END

u2 = User.from_xml(<<~END)
  <user>
    <first_name>John</first_name>
    <last_name>Doe</last_name>
  </user>
END

p u1 == u2
# => true

```

**Comment by TastyPi** [comment]
@kgiszczak yes, along with `eql?` and `hash`. I've made a quick implementation that uses `to_hash`:

```ruby
def ==(other)
  self.class == other.class && to_hash == other.to_hash
end
alias_method :eql?, :==

delegate :hash, to: :to_hash
```

My use case is asserting objects are equal in tests, so I'm not too worried about performance, but probably something to consider properly for a "native" implementation.

> Or if there is a recommended alternative for automatically implementing equality that could be documented that would be useful.

This comment is just because back in my days writing Java code it was super easy to implement `equals` and `hashCode` using `Objects.equals` and `Objects.hashCode`, I guess the Ruby equivalent would be using Arrays.

**Comment by kgiszczak** [comment]
Hmm, Shale mapper creates a new object every time it's executed, I'm not sure making them equal is the right approach.
If you create a new instance of the same class in ruby they also are not equal. It may be confusing imo.

You can also plug in your own model class, in which case Shale would have to modify this custom class to be consistent.

My suggestion would be to use `.to_hash` to check for equality, e.g:
```ruby
User.to_hash(u1) == User.to_hash(u2)
```
That would probably be the easiest approach.
