### ISSUE TITLE
Attribute Type Registry

### ISSUE THREAD

**Issue by admtnnr** [kgiszczak/shale#43]
Hey Kamil! I just started using Shale to clean up our in-house API clients and so far things are going well! I was wondering if you would be open to introducing an attribute type registry/lookup table to make the Shale mapping process a bit less verbose and streamline the UX?

I'm imagining something similar (if not the exact same) as what [`ActiveModel::Attributes`](https://api.rubyonrails.org/classes/ActiveModel/Attributes.html) does with the symbol to type lookup done through [`ActiveModel::Type`](https://github.com/rails/rails/blob/a11f0a63673d274c59c69c2688c63ba303b86193/activemodel/lib/active_model/type.rb)'s `lookup` and `register` methods. That would allow us to do something like the following which I personally think cuts down on the cognitive overhead and makes reading the class a little easier. What do you think? I'm happy to submit a PR if you're open to it.

```ruby
class Person < Shale::Mapper
  attribute :first_name, :string
  attribute :last_name, :string
  attribute :date_of_birth, :date
end

**Comment by kgiszczak** [comment]
Hey, PR is welcome

**Comment by admtnnr** [comment]
@kgiszczak PR has been opened, let me know what you think. 🙂

**Comment by kgiszczak** [comment]
Thank you, I'll review it through the weekend.
