### ISSUE TITLE
Allow to partial render

### ISSUE THREAD

**Issue by Tab10id** [kgiszczak/shale#5]
Sometimes we need to render only partion of available attributes.
For now we use representable for such things:
https://trailblazer.to/2.1/docs/representable.html#include-and-exclude
https://trailblazer.to/2.1/docs/representable.html#representable-function-api-skip-render
Do you have plans to implement this or maybe there is some hacky solution?

**Comment by kgiszczak** [comment]
Thanks for suggestions, there shouldn't be a problem implementing it. I should have something after weekend.

**Comment by kgiszczak** [comment]
Hey, I just released a new version that adds partial renders. Release notes are here: https://www.shalerb.org/releases.html#v070

I'll close the issue, if you need anything create a new one, thanks.

**Comment by Tab10id** [comment]
Thanks for release. Nice work!
