### ISSUE TITLE
JRuby support

### ISSUE THREAD

**Issue by risen** [kgiszczak/shale#8]
Hello,

In v0.5.0 you dropped Ruby 2.6 support, which implicitly also dropped JRuby support: as of JRuby 9.3.6.0 they're still only 2.6 compatible. Would it be possible to restore this easily? Are you currently using 2.7-only features?

JRuby 9.4.0.0 will Ruby 3.1 compatible, but it might take a while still to be released and for codebases to be able to make a smooth transition to it.

Thanks for your consideration!

**Comment by kgiszczak** [comment]
Hey, just pushed a change that brings back Ruby 2.6 support to master. I'll cut a release later this week.

**Comment by risen** [comment]
Wow, thank you!
